name: automerge
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress,!wip"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_FORKS: "false"
          MERGE_DELETE_BRANCH: "false"
